Repository RitehWebTeam/infobip-rimatch, pull requests merged in 2024-06, with the labels that each got.

#132 Potential users tests
  backend/pom.xml
  backend/src/main/java/com/rimatch/rimatchbackend/configuration/AppConfiguration.java
  backend/src/main/java/com/rimatch/rimatchbackend/model/Preferences.java
  backend/src/main/java/com/rimatch/rimatchbackend/model/User.java
  backend/src/main/resources/test.properties
  backend/src/test/java/com/rimatch/rimatchbackend/PotentialMatchingIntegrationTests.java
  backend/src/test/java/com/rimatch/rimatchbackend/RimatchBackendApplicationTests.java
  backend/src/test/java/com/rimatch/rimatchbackend/services/MatchServiceTest.java
Labels: for: API, type: testing

#135 Blocked user list endpoint
  backend/src/main/java/com/rimatch/rimatchbackend/controller/UserController.java
  backend/src/main/java/com/rimatch/rimatchbackend/service/UserService.java
Labels: for: API

#138 Added functional blocked users list
  frontend/src/api/users.ts
  frontend/src/main.tsx
  frontend/src/views/settings/SettingsBlockedUsers.tsx
  frontend/src/views/settings/SettingsList.tsx
Labels: type: feature

#133 Reporting user backend
  backend/src/main/java/com/rimatch/rimatchbackend/controller/ReportController.java
  backend/src/main/java/com/rimatch/rimatchbackend/model/Report.java
  backend/src/main/java/com/rimatch/rimatchbackend/repository/ReportRepository.java
  backend/src/main/java/com/rimatch/rimatchbackend/service/ReportService.java
Labels: type: feature

#140 Websocket image upload
  .editorconfig
  backend/src/main/java/com/rimatch/rimatchbackend/RimatchBackendApplication.java
  backend/src/main/java/com/rimatch/rimatchbackend/controller/MessageController.java
  backend/src/main/java/com/rimatch/rimatchbackend/controller/UserController.java
  backend/src/main/java/com/rimatch/rimatchbackend/controller/WebSocketController.java
  backend/src/main/java/com/rimatch/rimatchbackend/dto/MessageDTO.java
  backend/src/main/java/com/rimatch/rimatchbackend/model/Match.java
  backend/src/main/java/com/rimatch/rimatchbackend/model/Message.java
  backend/src/main/java/com/rimatch/rimatchbackend/model/MessageType.java
  backend/src/main/java/com/rimatch/rimatchbackend/service/S3Service.java
  frontend/frontend.iml
  frontend/src/api/messages/messages.ts
  frontend/src/api/messages/strategies/ImageMessageHandler.ts
  frontend/src/api/messages/strategies/MessageHandler.ts
  frontend/src/api/messages/strategies/TextMessageHandler.ts
  frontend/src/api/users.ts
  frontend/src/components/ChatListComponent.tsx
  frontend/src/components/ChatMessageRecived.tsx
  frontend/src/components/ChatMessageSent.tsx
  frontend/src/components/ProfileCard.tsx
  frontend/src/components/ScrollToFieldError.tsx
  frontend/src/components/chat/ChatHistory.tsx
  frontend/src/components/chat/ChatInput.tsx
  frontend/src/components/chat/ChatMessage.tsx
  frontend/src/types/Message.d.ts
  frontend/src/types/Message.ts
  frontend/src/views/ChatPage.tsx
  frontend/src/views/ListOfMatchesForChatPage.tsx
  frontend/src/views/chat/ChatLayout.tsx
  mobileV2/mobileV2.iml
  mobileV2/src/api/messages.ts
  mobileV2/src/api/users.ts
  mobileV2/src/app/(Forms)/SetupPreferences/(steps)/Step4Preference.tsx
  mobileV2/src/app/(Forms)/SetupPreferences/store.tsx
  mobileV2/src/app/(Protected)/(tabs)/Matches.tsx
  mobileV2/src/app/(Protected)/(tabs)/Settings/(screens)/Gallery.tsx
  mobileV2/src/app/(Protected)/(tabs)/Settings/(screens)/ProfilePicture.tsx
  mobileV2/src/app/(Protected)/(tabs)/Settings/(screens)/Theme.tsx
  mobileV2/src/app/(Protected)/(tabs)/Settings/(screens)/UserSettings.tsx
  mobileV2/src/components/GenderPicker.tsx
  mobileV2/src/components/MatchCard.tsx
  mobileV2/src/components/ProfileCard.tsx
  mobileV2/src/context/ThemeProvider.tsx
  mobileV2/src/hooks/useTheme.tsx
  mobileV2/src/types/Message.d.ts
  mobileV2/src/types/Message.ts
  mobileV2/src/types/User.d.ts
Labels: for: Web App

#141 Update frontend packages
  app.json
  docker-compose.yaml
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: for: Web App, type: chore

#142 Setting dominant Navbar overlap
  frontend/src/components/Navbar.tsx
Labels: type: bug, for: Web App

#144 84-geolocation-front
  frontend/src/views/SetupPreferences/steps/Step1Preferences.tsx
Labels: for: Web App

#143 126-reporting-frontend
  frontend/src/api/users.ts
  frontend/src/components/Navbar.tsx
  frontend/src/components/UserActionsDropdown.tsx
  frontend/src/types/User.d.ts
Labels: for: Web App, type: feature
